/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.juhi.ws;
import javax.jws.WebService;

/**
 *
 * @author hrisabhy
 */
@WebService(endpointInterface="com.hrisabhy.ws.HelloWorld")
public class HelloWorldImpl implements HelloWorld{
    @Override  
    public String getHelloWorldAsString(String name) {  
        return "Hello World " + name + "-generated by soap ws";  
    }  
}